### ISSUE TITLE
Orion Camo Tracker Issues and Bugs

### ISSUE THREAD

**Issue by Pausbe** [carlssonemil/orion#1]
Thank you for another camo tracker for COD, this tracker has saved me so much time grinding camos. I am very grateful for your continued work on this. ♥

## Issues
-Platinum doesn't automatically unlock after completing all Gold guns in a category 

- Needs a button like Gold for the challenge

-Every gun in the same category doesn't always have the same challenge 

- Needs an override to add camo challenges for certain guns

## Bugs
-Hide completed filter does not work

-Adding a Gold requirement in `src\data\requirements.js` does not work 

## Suggestions

-Add Gold, Plat Progress Bar at the bottom since...

1. You need to go out of your way to get the camo for every gun
2. The Orion progress bar doesn't progress until you start ticking off the Polyatomic boxes

Also probably a way to hide them since it could take up a bit of screen space.

## 

I now know why developers hate QA 🤣
I'll make sure to buy you a coffee sometime!

**Comment by carlssonemil** [comment]
Thanks for your continued help throughout they years with the trackers! No need to buy me a coffee, I should be the one to buy you one! 😄 

I'll look through the issues and bugs after work today and tomorrow! About the suggestion, the current way the progress is calculated is not ideal and I'll look into other solutions during the coming weeks where each and every camouflage counts towards the overall progress. I could however add a Gold progress bar for the time being just so it doesn't stay at 0 🤔

**Comment by carlssonemil** [comment]
All issues and bugs should now be resolved. I'll look into the suggestion! Closing this issue as fixed 🥳
