### ISSUE TITLE
Remove DOOM Chainsaw from the list since it's just a Pickaxe skin

### ISSUE THREAD

**Issue by alvinpeters** [carlssonemil/orion#109]
If I got the time I can make the PR later today.

![image](https://github.com/carlssonemil/orion/assets/111344576/c6d20598-6a7e-4003-aea6-d6c962a8c195)

![image](https://github.com/carlssonemil/orion/assets/111344576/df7f5bb3-c7a8-4745-82d4-342529926d89)

**Comment by jamesallnutt** [comment]
@striczkof Done #113

**Comment by striczkof** [comment]
> @striczkof Done #113
cheers mate!

**Comment by alvinpeters** [comment]
> @striczkof Done #113

cheers mate!
