### ISSUE TITLE
Your error stating that comingSoon isn't defined on https://orion.emca.app

### ISSUE THREAD

**Issue by C0deS3rp3nt** [carlssonemil/orion#114]
I don't usually use github so pardon me for doing this under the issues thing. When I was going through and pushing this through debug that's when I found that it wasn't defined, I went to the melee.js file and it seems you just forgot to define the comingSoon variable although you probably already know but here's the definition **"var comingSoon = [];"**

**Comment by jamesallnutt** [comment]
#115 Created this pull request @C0deS3rp3nt

**Comment by carlssonemil** [comment]
Fixed by #115. Thanks for reporting! 😄
