### ISSUE TITLE
Incorrectly Named Calling Card Images Causing Non-Load (Green Box)

### ISSUE THREAD

**Issue by jamesallnutt** [carlssonemil/orion#117]
A handful of calling cards are returning the below:

![image](https://github.com/carlssonemil/orion/assets/41279064/f30934f1-a883-404e-9722-47322d8c2a15)

This is occurring for the following:

 **Longshots**

- Vengeful Stance (500 Longshots)
- God of Death (1000 Longshots)

**Prestige 8**

- Grim Fate (15 Quad Kills)
- Chattering Soldier (100 Operator Headshots)

**Prestige 9**

- Hold your fire (10 operator kills without dying 10 times)

**Prestige 12**

- It Beings Here (Get 100 Operator One Shot One Kills with Shotguns)
- Rusher Mentality (Disrupt 50 Operator Equipment with DDoS)

**Prestige 22**

- Animal Instinct (Complete All Prestige Challenges)

**Prestige 23**

- Eat Lead! (Complete All Prestige Challenges)

**Prestige 24**

- Gotchya! (Get 25 Operators Kills by Sticking them with Thermite)

**Comment by jamesallnutt** [comment]
Should be fixed by #119 - Latest tests locally show images loading aside from 4 which once pushed to the hosting, should work as the naming convention is updated.

**Comment by carlssonemil** [comment]
Should be fixed by #119. I'll confirm later when the cache clears.
