### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mrsloth4994** [carlssonemil/orion#15]
Could it be possible for you to add this website into a exe file. I think an exe file would be more appropriate for this type of thing. Just a suggestion as stated. love your work.

**Comment by carlssonemil** [comment]
Hey! Thanks for the suggestion, but what is the use case for this? What do we gain by opening it as an `.exe` instead of in a browser? 😄

**Comment by mrsloth4994** [comment]
> Hey! Thanks for the suggestion, but what is the use case for this? What do we gain by opening it as an `.exe` instead of in a browser? 😄 

Personally, I prefer to have exe on my desktop and in a single click it's open. Exe in my opinion is just better than having a tab open for a website and I know that exe runs faster and more smoother than websites. But hey, other people may have different opinions on my suggestion

**Comment by carlssonemil** [comment]
There are a few ways to convert web apps to native applications. Using [Electron](https://www.electronjs.org/) would probably be the easiest. I'm not promising anything, as it's a lot of work, but I'll look into it!

**Comment by sol3uk** [comment]
Might be nice to add PWA style caching to make it viable as a totally client side app, and should massively improve performance on multiple reloads and make it available when offline, but can't see any value being added from an OS specific application launcher. 😖

**Comment by carlssonemil** [comment]
> Might be nice to add PWA style caching to make it viable as a totally client side app, and should massively improve performance on multiple reloads and make it available when offline, but can't see any value being added from an OS specific application launcher. 😖

PWA caching shouldn't be too hard to add actually. Could potentially run into some hard-to-clear-cache issues down the road, but it would definitely help with performance.

**Comment by sol3uk** [comment]
If you use the correct caching strategy you can force it to update the cache when you update the app and change the cache name etc, I think there's a few ways to do it. 

This article is my go-to:
https://developer.chrome.com/docs/workbox/caching-strategies-overview/
