### ISSUE TITLE
Suggestion: List View

### ISSUE THREAD

**Issue by gesunTight** [carlssonemil/orion#19]
Hey Emil,

love your tracker.

Is it possible to add an option to show each camo requirement as text so i don't have to mouse over?

Ty

**Comment by sol3uk** [comment]
I knew it was coming @carlssonemil 😄 I think we mentioned this previously about the challenges etc being always visible but more in the context of mobile specific optimisations. I'm not a design expert but would love to put something together, if anyone wants to help me out with some inspiration I'll pop a PR together! 🤔
