### ISSUE TITLE
Filter Suggestion

### ISSUE THREAD

**Issue by gamingoffice** [carlssonemil/orion#24]
A filter to just show the wepons that are already 
Maxxed 
Gold 
PLAT

etcetera i think you got what i mean

**Comment by carlssonemil** [comment]
Why would you want to see just your completed weapons? 😅

**Comment by gamingoffice** [comment]
To have a nice overwiev of which weapons are already done with this and this camoAm 17.11.22, 21:34 schrieb Emil Carlsson ***@***.***>:

   
  Why would you want to see just your completed weapons? 😅

**Comment by carlssonemil** [comment]
I'll think about it! 😄
