### ISSUE TITLE
Bug - Import issues

### ISSUE THREAD

**Issue by sol3uk** [carlssonemil/orion#26]
I noticed when importing that the initial import either from file or pressing "Import code" doesn't trigger a call to save to local storage (haven't double checked in code yet), as when I reload the changes aren't retained.
Also the "Import code" button doesn't seem to fire a notification like the "Import from file" does.

![brave_zYVzatzUkC](https://user-images.githubusercontent.com/26093813/202808897-b36c07f4-9045-4587-a40f-959bb4da68c0.gif)

**Comment by carlssonemil** [comment]
Nice find! 👍
