### ISSUE TITLE
APK suggestion 

### ISSUE THREAD

**Issue by iTzGhemon19** [carlssonemil/orion#27]
hello, my suggestion is if it's not so much complicated to create a little APK file so i can access trough my phone

**Comment by carlssonemil** [comment]
If you access the tracker website on your phone and save it as a bookmark to your home screen, it will technically function as a normal app! 😄

**Comment by iTzGhemon19** [comment]
yeah, but the convenience of having it also available offline is awesome

**Comment by florensie** [comment]
I'd say that's a pretty limited use case, since you won't be able to unlock any camos anyways if you're somewhere without an internet connection.

**Comment by carlssonemil** [comment]
We have discussed adding PWA caching, which would make the website work even offline. But as @florensie commented, why would you want to track your progress on the tracker when you can't even play due to no internet access? 🤔

**Comment by iTzGhemon19** [comment]
maybe it's just only me that I prefer the APK over the site
