### ISSUE TITLE
Wrong skin name

### ISSUE THREAD

**Issue by cpjet64** [carlssonemil/orion#34]
For the Minibak ingame it is called "Stoked Flame" but on the site "https://orion.emca.app/" it is called "Skyfire" 
![Screenshot_4](https://user-images.githubusercontent.com/38527447/204098740-a42af018-0108-4fcb-a251-f53bc675807b.png)
CoD MW2 2022

**Comment by cpjet64** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/38527447/204098835-3efb61a7-8f82-4650-9a8e-b03483ed8f93.png)
Sorry for the second post it wouldnt let me upload another screenshot in my initial post for some reason.

**Comment by cpjet64** [comment]
Same name issue with the PDSW 
![Screenshot_7](https://user-images.githubusercontent.com/38527447/204098895-ac01e542-f10c-4954-90fa-96ce71aeac19.png)
![Screenshot_6](https://user-images.githubusercontent.com/38527447/204098896-155d54c2-14cc-435f-83cb-cd23a2da2e62.png)

**Comment by cpjet64** [comment]
Same with the RAAL MG
![Screenshot_9](https://user-images.githubusercontent.com/38527447/204099068-618f0437-e5fa-4404-8ada-ef491bdd173b.png)
![Screenshot_8](https://user-images.githubusercontent.com/38527447/204099069-168a3bc9-a739-40f5-8a87-d58b5b88dfb6.png)

**Comment by sol3uk** [comment]
Damn they really updated a bunch of camo names didn't they!

**Comment by cpjet64** [comment]
I'm sure theres more since I didnt check every single skin name but I can go back over everyone of them if it helps. This site is the best and its so well organized!!!!

**Comment by carlssonemil** [comment]
Thanks for letting me know! I'll fix them real quick!

**Comment by carlssonemil** [comment]
Also, you seem to have unlocked a lot of camouflages that we're missing the images for. Would you mind screenshotting them in-game and emailing them to me at hello@emilcarlsson.se? I'd really appreciate it! 😄

**Comment by carlssonemil** [comment]
Should be fixed now!

For future reference @sol3uk, I've added a file ([camouflageNameChanges.js](https://github.com/carlssonemil/orion/blob/main/src/data/camouflageNameChanges.js)) where we can keep track of name changes to camouflages so that the progress get's migrated over seamlessly 😄

**Comment by cpjet64** [comment]
[MW2SS.zip](https://github.com/carlssonemil/orion/files/10097407/MW2SS.zip)
[MW2SS#2.zip](https://github.com/carlssonemil/orion/files/10097426/MW2SS.2.zip)

These are screenshots of all the Camos I have unlocked so far. Sorry they aren't all the exact same size or trimmed but I am working on a way to extract the images directly from the game files. If I'm successful I will upload them here for you. Keep up the great work on the tool!

A suggestion I might add is some of the weapons are out of order on the site compared to the game. Here is a full list in order from the game.

Assault Rifles
M4
TAQ-56
Kastov 762
Lachmann-556
STB 556
M16
Kastov-74U
Kastov 545
M13B

Battle Rifles
Lachmann-762
SO-14
TAQ-V
FTAC Recon

SMGs
VEL 46
MX9
Lachmann Sub
Vaznez-9K
FSS Hurricane
Minibak
BAS-P
PDSW 528
Fennec 45

Shotguns
Lockwood 300
Expedite 12
Bryson 800
Bryson 890

LMGs

Sakin MG38
HCR 56
556 Icarus
RAL MG
RPK
RAPP H

Marksman Rifles
EBR-14
SP-R 208
Lockwood MK2
LM-S
SA-B 50
TAQ-M

Sniper Rifles
MCPR-300
Victus XMR
Signal 50
LA-B 330
SP-X 80

Melee
Riot Shield
Combat Knife

Handguns
P890
.50 GS
X12
Basilisk
X13 Auto

Launchers
Pila
Strela-P
JOKR
RPG-7

**Comment by cpjet64** [comment]
OK so I was able to extract everything but the filenames are all hashed so I have to go through every image to find them. If you want to help just let me know!

**Comment by sol3uk** [comment]
> Should be fixed now!
> 
> For future reference @sol3uk, I've added a file ([camouflageNameChanges.js](https://github.com/carlssonemil/orion/blob/main/src/data/camouflageNameChanges.js)) where we can keep track of name changes to camouflages so that the progress get's migrated over seamlessly 😄

@carlssonemil  I think ideally the camos would use IDs to be tracked as progress, rather than the name. They could continue to name change in the future or mess up the names etc. Would be better to get IDs sorted then we wouldn't have to worry in the future?

**Comment by carlssonemil** [comment]
> > Should be fixed now!
> > For future reference @sol3uk, I've added a file ([camouflageNameChanges.js](https://github.com/carlssonemil/orion/blob/main/src/data/camouflageNameChanges.js)) where we can keep track of name changes to camouflages so that the progress get's migrated over seamlessly 😄
> 
> @carlssonemil I think ideally the camos would use IDs to be tracked as progress, rather than the name. They could continue to name change in the future or mess up the names etc. Would be better to get IDs sorted then we wouldn't have to worry in the future?

Ideally, yes, but we would need to completely re-write the way camouflages are defined and preferably add automatic ID logic so we don't have to manually keep track. Adding an API on top of this connecting to a Postgres database just for camouflages would solve a lot of this automatically for us 🤔 

But we would also still need to migrate any old progress for probably months to come (some people pause their tracking for months, myself included 😅), keeping a similar list of name changes as defined in [camouflageNameChanges.js](https://github.com/carlssonemil/orion/blob/main/src/data/camouflageNameChanges.js) anyways (or possibly add an alias property to the camouflage object with all previous names 🤔).

I think the [solution I added yesterday](https://github.com/carlssonemil/orion/commit/0af8a1d4074c5c89a87c3b8b1161b31e617fdfdd) will work for now. But I'll open an issue for it and put it in the backlog for future reference! In the next Call of Duty I'm gonna plan out the data structure taking all of these issues into account 😄 Previous Call of Duties didn't require this level of complexity.
