### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by cpjet64** [carlssonemil/orion#35]
Make a "pinned" camo section where you can select up to 3 or so camos that you are working on such as a primary rifle and a secondary pistol that pin to the top of the page.

**Comment by sol3uk** [comment]
If you go to the camouflage page, there's an option to "favourite" camos that will appear at the top @cpjet64

**Comment by sol3uk** [comment]
Would it make sense to have a similar section for weapons @carlssonemil? I.e. a favourites section for weapons you're currently working on.
I'd definitely use that.

**Comment by cpjet64** [comment]
I see what you are talking about. From my perspective of completionism I want to unlock all unique camos across all weapons now that I have max leveled all weapons. So being able to stay on the weapons page would be a huge plus. Instead of a massive list of everything it would be nice to focus on a section where it only contains the weapons I'm currently working on and as I complete camos for the ones I'm currently working on I can checkmark them right there as well.

**Comment by carlssonemil** [comment]
A favorite section for weapons as well is definitely a great idea! I'll take a look at it! 😄 👍
