### ISSUE TITLE
Weapon Mastery Tracking (Feature Suggestion)

### ISSUE THREAD

**Issue by Pausbe** [carlssonemil/orion#37]
It would be nice to have weapon mastery tracking, similar to the Damascus tracker.
They've also made it simple this time around, only requiring kills with a specific camo equipped.

![image](https://user-images.githubusercontent.com/74504687/204165038-c86043b5-dd54-4659-abba-c845045ff6be.png)

**Comment by carlssonemil** [comment]
I'll definitely look into adding this! Might need some help gathering all the mastery challenges though 🤔

**Comment by Pausbe** [comment]
Good news! The mastery challenges are the same for every weapon.

Gold Mastery: Get 100 Kills while using the Gold Camo
Platinum Mastery: Get 200 Kills while using the Platinum Camo
Polyatomic Mastery: Get 300 Kills while using the Polyatomic Camo
Orion Mastery: Get 400 Kills while using the Orion Camo

**Comment by sol3uk** [comment]
> Orion Mastery: Get 100 Kills while using the Orion Camo

I assume this should be 400?

**Comment by Pausbe** [comment]
> > Orion Mastery: Get 100 Kills while using the Orion Camo
> 
> I assume this should be 400?

Yep, went a bit too fast writing that...😅
