### ISSUE TITLE
Camouflage Images - Contributing Guidelines

### ISSUE THREAD

**Issue by MaxJW** [carlssonemil/orion#40]
I noticed there were a few missing camouflage images from the tracker and wanted to contribute them, but I'm not sure of the process for adding them! Do you just screenshot them in game? And is there a specific naming convention for the images themselves?

It would be great to have some guidelines in CONTRIBUTING.md for this!

**Comment by carlssonemil** [comment]
Correct, I screenshot them in-game and then crop them out so there's no borders or background - preferably they should be 1x1 format, but it's not required. [Photopea](https://www.photopea.com/) is an amazing free Photoshop alternative for image editing. The naming convention should follow the [slug-format](https://en.wikipedia.org/wiki/Clean_URL#Slug) and preferably be in `.png` file format (`Desert Hybrid` -> `desert-hybrid.png`). The finished image files should be placed in `src/assets/camouflages`.

I'll update the contributing guidelines with a specific section for just camouflage images! Great suggestion!

I'll also happily accept just the screenshots on my email (hello@emilcarlsson.se) and I'll edit and add them myself! 😄 

I haven't had as much time as I would've liked grinding the camouflages in this game, so I'm slacking behind on the images as I haven't unlocked them myself 😅
