### ISSUE TITLE
Suggestion / Accessibility Improvement - Category Totals Readability

### ISSUE THREAD

**Issue by sol3uk** [carlssonemil/orion#44]
Currently the weapon category total is only the max number of guns you need to get in order for it to be done in that category, however, since there are more weapons in the category now, due to DLC, this can be confusing unless you already know about the grind and or you figure out you can hover over the total like so:

![image](https://user-images.githubusercontent.com/26093813/204670649-0bfaab4c-ed38-41b8-98aa-abed23077b90.png)

I would suggest that we find another way to display the progress, maybe show the total guns completed and the total in the category, but then we maybe show the number going gold when the user has completed the appropriate number of guns for the platinum challenges? Obviously the hover tooltip is still useful, we could just reword it.

(Bad mockup incoming, the tooltip should show the number of gold weapons needed)

![image](https://user-images.githubusercontent.com/26093813/204671822-7b5b0190-095c-4dd3-b24a-0d0a8463ecc7.png)

**Comment by carlssonemil** [comment]
In #39 I change this text (and counter) to "Weapons completed in category" instead, since it'll probably be more useful. But we could definitely add a different color for different "states"! 👍
