### ISSUE TITLE
MCPR-300 Plat Challenge Wrong

### ISSUE THREAD

**Issue by Noriaela** [carlssonemil/orion#51]
![cod_srR932PCut](https://user-images.githubusercontent.com/22671423/205447123-afe7406c-3cd6-409c-aec4-59bcffb813ba.png)
![firefox_Z2OZQqlnh6](https://user-images.githubusercontent.com/22671423/205447140-9d551466-55a3-405f-82f6-d639be053c79.png)

**Comment by carlssonemil** [comment]
Is it only for the MCPR-300 or are all sniper platinum challenges only 20 longshot kills?

**Comment by Noriaela** [comment]
> Is it only for the MCPR-300 or are all sniper platinum challenges only 20 longshot kills?

Just saw this.

The only other Sniper with 20 longshots is the Signal.

![cod_ChaNFVUsTP](https://user-images.githubusercontent.com/22671423/205545223-e0412f95-55e1-461a-986a-ff2e228e2845.png)

**Comment by carlssonemil** [comment]
> The only other Sniper with 20 longshots is the Signal.

I'll fix that as well after work later today! 😄
