### ISSUE TITLE
Camo images for the new Chimera not showing

### ISSUE THREAD

**Issue by Bjelke98** [carlssonemil/orion#59]
Camo images for the new Chimera not showing
I assume the files are not available yet.

**Comment by carlssonemil** [comment]
Correct! Once we have them they will be added! 😄

**Comment by whyyn0tt** [comment]
> Correct! Once we have them they will be added! 😄

I'm in the process of completing the Chimera camos now, if you need images just let me know how I can help.

**Comment by carlssonemil** [comment]
> I'm in the process of completing the Chimera camos now, if you need images just let me know how I can help.

Nice, @whyyn0tt! Feel free to screenshot them ingame and email them to me and I'll add them! We'll try and find the original images later! 😄

**Comment by whyyn0tt** [comment]
> > I'm in the process of completing the Chimera camos now, if you need images just let me know how I can help.
> 
> Nice, @whyyn0tt! Feel free to screenshot them ingame and email them to me and I'll add them! We'll try and find the original images later! 😄

Just sent them over!
