### ISSUE TITLE
Polyatomic - Hide Polyatomic breaks and hides the button for all non-achieved

### ISSUE THREAD

**Issue by sol3uk** [carlssonemil/orion#6]
# Before filtering:
![image](https://user-images.githubusercontent.com/26093813/200400147-5c89b7c3-2487-4529-8ebe-1fd55627e73f.png)

-------------------------------------------------------------

# After filtering (Should keep the button to allow you to check them off):
![image](https://user-images.githubusercontent.com/26093813/200400206-a736e0ee-3bac-46e3-898d-2457a21fc646.png)

**Comment by carlssonemil** [comment]
Is this still an issue, @sol3uk? 🤔
