### ISSUE TITLE
is polyatomic still being added

### ISSUE THREAD

**Issue by littlebeastman05** [carlssonemil/orion#7]
i cant find it on the site is it still being added to the website

**Comment by carlssonemil** [comment]
Hey! Polyatomic is added to the site, it will be visible once you have completed every Platinum camouflage on the guns. See this page for more details:

https://orion.emca.app/requirements

It is hidden up until you have completed 51 platinum camouflages because why show it until it's available? 😉

**Comment by carlssonemil** [comment]
I changed so that Polyatomic is now always visible! 😄
