### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LukeSetzer** [carlssonemil/orion#74]
you only need to have 51 guns to Polyatomic to reach ORION not 55

**Comment by carlssonemil** [comment]
Correct! I'm guessing you are referring to this:

![Screenshot 2023-02-15 at 11 12 36](https://user-images.githubusercontent.com/10532336/218998696-57eabe71-f7d3-4641-b16e-4f9a04376568.png)

This is just an overview of how many weapons in total you have completed each of the camouflages for, not an overview how many you need for the Orion camouflage. The percentage progress at the bottom of the page indicates the progress towards Orion.

Hope that clears it up! 😄

**Comment by LukeSetzer** [comment]
Ahh i see 👍 thanks!
