### ISSUE TITLE
[FEATURE] Calling Card Tracker

### ISSUE THREAD

**Issue by smcnab1** [carlssonemil/orion#75]
I currently use a Google Doc which covers all weapons and calling cards. I have recently transitioned to this tracker for camos but would be nice to have a calling card tracker to bring all into one.

![Screenshot 2023-02-19 at 11 41 32](https://user-images.githubusercontent.com/108990188/219945701-d32bcbda-82c2-4ca2-809c-733072a2475d.png)

**Comment by carlssonemil** [comment]
I'll look into it! It's a lot of work collecting all the data though for all the calling cards, so might take some time to gather and organize everything into the tracker! 😄

**Comment by smcnab1** [comment]
> I'll look into it! It's a lot of work collecting all the data though for all the calling cards, so might take some time to gather and organize everything into the tracker! 😄 

Let me know if I can help at all! More than happy to

**Comment by sol3uk** [comment]
I did a challenge tracker as part of a previous app, feel free to take a look 😄 
You might not want to go as far as I did with the navigation and browser history, but I just went for the basics like the ability to pin a challenge and display the calling cards.
https://declassified.netlify.app/challenge

**Comment by carlssonemil** [comment]
I opened a PR for the new feature so we can test it before publishing to the tracker. Feel free to try it out and give feedback if needed. I'll merge it in a few days if no issues arise. The preview can be found here: 
- https://orion-git-feature-calling-cards-emca.vercel.app/

**Comment by smcnab1** [comment]
> 

Looks good, would be interesting to have it like Camos where they are in their categories. Like on the Customise section on the game, each section works towards the mastery calling card of that category if that makes any sense. But cracking and super fast addition!

**Comment by carlssonemil** [comment]
> Looks good, would be interesting to have it like Camos where they are in their categories. Like on the Customise section on the game, each section works towards the mastery calling card of that category if that makes any sense. But cracking and super fast addition!

I haven't actually checked in-game how it's made, I just got the list from here: http://www.vhpg.com/mw2-calling-card/, and used the general categories defined there.

We could absolutely categorize the calling cards differently if it helps with the tracking 😄 Should I categorize them according to their mastery category? For example:
- Operator Kills
- Operator Assists
- Etc..

**Comment by smcnab1** [comment]
> 

Yeah I think per master category like DMZ cash exfil there would be 4 plus a mastery card

**Comment by carlssonemil** [comment]
Just a follow up, I haven't forgotten about this, just haven't found the time to categorize the challenges yet! 😄

**Comment by carlssonemil** [comment]
Sorry for the delay, should be fixed now! 😄

**Comment by smcnab1** [comment]
> Sorry for the delay, should be fixed now! 😄

Legend! Looks great
