### ISSUE TITLE
Feature Suggestion - Weapon levels tracker

### ISSUE THREAD

**Issue by walnuts84** [carlssonemil/orion#8]
Thanks for making this app, usually I am the one in my group to find handy things like this. 
This time one of those I never expected was into it, shared the link to Orion tracker =) People definitely love this. 

My suggestion is to make a similar tracker, but for leveling the weapons. 
Version 1: Small boxes under each weapon that you check off. 
Version 2: A field where you also input operator level and battle passes, and their levels. 
Certain weapons are greyed out / or say the background changes color when those weapons are locked. 
They can become unlocked by examples: 
- IF the operator is at a certain level
- If battle pass for season 5 is at a certain level
- If a specific weapon requires another weapon to be at a certain level (receiver families progression).

**Comment by carlssonemil** [comment]
Definitely an interesting suggestion! I'll think about it! 😄

**Comment by sol3uk** [comment]
Maybe adding all this to a camo tracker is a bit too much bloat? With a lot of the attachments being shared and linked to guns and also the weapon platforms being a thing now, this could basically be it's own app all to itself! 😬
Would still be interesting to work on though!
