### ISSUE TITLE
[Bug] Camos

### ISSUE THREAD

**Issue by Butterb22** [carlssonemil/orion#87]
The camos for the Cronen Squall, FJX Imperium, FTAC Siege and GS Magna aren't showing up as the camos, its just a neon green square
![image](https://github.com/carlssonemil/orion/assets/34287074/38a8acff-4243-464c-bc79-3e03e20fc0d0)
![image](https://github.com/carlssonemil/orion/assets/34287074/d5664dba-e67c-4a4c-81af-b724b4677461)
![image](https://github.com/carlssonemil/orion/assets/34287074/d080ebfb-de62-4c6b-88ff-d4bd8f91639a)
![image](https://github.com/carlssonemil/orion/assets/34287074/5d7f6738-afa3-40af-a148-bdc9dd62a60f)
![image](https://github.com/carlssonemil/orion/assets/34287074/0b019bd5-8c07-406f-bd25-e6d4c067e24e)
![image](https://github.com/carlssonemil/orion/assets/34287074/7aa22dcc-0951-49c7-be8d-40bf6871f46e)
![image](https://github.com/carlssonemil/orion/assets/34287074/5e9f3c7c-a9f0-4684-b482-48d3cf882fea)
![image](https://github.com/carlssonemil/orion/assets/34287074/4c784b9d-97f5-4194-ab05-ea7e2b911cb4)
![image](https://github.com/carlssonemil/orion/assets/34287074/f6ac0728-e754-4454-b5c1-3165eb042095)

**Comment by carlssonemil** [comment]
Thanks for reporting! I'll fix them as soon as I get the images! 😄

**Comment by whyyn0tt** [comment]
@carlssonemil here are the (16) latest for the Cronen Squall, FJX Imperium, FTAC Siege and GS Magna. Let me know if I can help further...I'm in the game (much too) often :]

edit: added latest event camo (Skull Eater)

**Cronen Squall:** 
![vapor-storm](https://github.com/carlssonemil/orion/assets/3478819/3cd14e57-18ae-4586-8ceb-5b1c1dcb5d1a)![ghastly-green](https://github.com/carlssonemil/orion/assets/3478819/81cabebc-a9be-4362-b07c-4440bf49522f)![stone-ridge](https://github.com/carlssonemil/orion/assets/3478819/3e739760-52e4-4e38-b6c8-4f1c62e1e901)![intergalactic](https://github.com/carlssonemil/orion/assets/3478819/0e8dabf3-12a1-4e40-a53b-54991f9d156b)
**FJX Imperium:**
![arctic-growth](https://github.com/carlssonemil/orion/assets/3478819/879d23be-7cb4-4b66-9160-670b9cf279ea)![styx](https://github.com/carlssonemil/orion/assets/3478819/a343e10f-6118-4a2a-ae0d-f62b10875e44)![psychoactive](https://github.com/carlssonemil/orion/assets/3478819/55337826-8139-46b6-a583-688e9e8b17ad)![bedlam](https://github.com/carlssonemil/orion/assets/3478819/473af8de-351a-4b6f-b8bd-5d8988216417)
**FTAC Siege:**
![sandpaper](https://github.com/carlssonemil/orion/assets/3478819/781796d8-0400-49ea-aa43-0e02ff4511fb)![velvet-midnight](https://github.com/carlssonemil/orion/assets/3478819/cb48bd33-5305-4d06-b08e-c412f36b3147)![painted-pig](https://github.com/carlssonemil/orion/assets/3478819/cd1cc298-300f-419e-a5a5-8556fe51f59a)![fuzzy-spectrum](https://github.com/carlssonemil/orion/assets/3478819/77692570-a15e-489a-bedb-8fb2e252ae78)
**GS Magna:**
![digital-wilds](https://github.com/carlssonemil/orion/assets/3478819/67568917-b651-4830-b9b6-274fa5a1abaa)![rhyolitic](https://github.com/carlssonemil/orion/assets/3478819/4d8d4a22-b690-44df-ab14-978834e8ef74)![cracking-onyx](https://github.com/carlssonemil/orion/assets/3478819/a313b9d8-9571-48d2-aec3-ad0f913a3673)![rad-reverb](https://github.com/carlssonemil/orion/assets/3478819/b933b1c6-fa37-49ee-a542-e4887de5bc5b)


_FYI - I also have the 4 special event camos, if they're useful:
![bowing-blossoms](https://github.com/carlssonemil/orion/assets/3478819/86f6d93f-01db-408f-b200-9c7ca79d3ca7)![dark-bones](https://github.com/carlssonemil/orion/assets/3478819/7d9a2f24-2ee7-4535-bf66-7227f69dd6c1)![winds-of-ash](https://github.com/carlssonemil/orion/assets/3478819/12ed4134-ac1b-48cf-b22b-5d1c324b20de)![skull-eater](https://github.com/carlssonemil/orion/assets/3478819/10c5520c-86e7-45e5-9aa7-2a95aa331692)

**Comment by carlssonemil** [comment]
Sorry for taking so long! The camouflage images should be visible on the app in a minute! 🚀 

@whyyn0tt, what's the name and unlock requirements for the special event camos? I can add them to their own section on the Camouflages page 😄
