### ISSUE TITLE
.editorconfig for easier contribution

### ISSUE THREAD

**Issue by Voigtus** [carlssonemil/orion#98]
Hello there,

I was just messing around and adding challenges, when my auto formatter hit me and changed the whole layout.
Not the nicest thing to happen. One of the things, that might help, is an ".editorconfig" file, which can be used by most IDEs to format the code as intended.

Just an idea for discussion

**Comment by carlssonemil** [comment]
Great idea! I'll look into adding it! Sorry for the late reply!
