### ISSUE TITLE
Add Season 5 Weapons

### ISSUE THREAD

**Issue by magnusfoldager** [carlssonemil/orion#99]

**Comment by Voigtus** [comment]
This is targeted in PR #97 
When one of the maintainer merges this change, at least the camo-challenges will be available. Albeit no camo images are available (still not have good images for that)

**Comment by magnusfoldager** [comment]
> This is targeted in PR #97 When one of the maintainer merges this change, at least the camo-challenges will be available. Albeit no camo images are available (still not have good images for that)

Gotcha - I was working on it myself as well. Will discard my fork.
